export { ReactComponent as XIcon } from './x.svg'
export { ReactComponent as BombIcon } from './bomb.svg'
export { ReactComponent as FlagIcon } from './flag.svg'
export { ReactComponent as SmileIcon } from './smile.svg'
export { ReactComponent as SadIcon } from './sad.svg'
